name: Test mathi second on docker
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["master"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: O-hazan/SecondMathi
      - name: Build the stack
        run: docker compose up --build --abort-on-container-exit
