name: Test mathi second on docker
on:
  push:
    branches: ["master"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the website
        uses: actions/checkout@v3
        with:
          repository: O-hazan/SecondMathi
      - name: Build stack and test
        run: docker compose up --build --abort-on-container-exit
